### ISSUE TITLE
Feature Request  - Channel Identification

### ISSUE THREAD

**Issue by joelprince25** [purdy/aws-transcribe-transcript#4]
Amazon Transcribe now enables channel identification. I was wondering if you were working on a similar script to make the channel output identification script more readable.

**Comment by purdy** [comment]
I'm not sure I've used that feature before. Do you have a sample input/output file?

**Comment by joelprince25** [comment]
`

`

**Comment by joelprince25** [comment]
Here's a sample input and output file. In this case, the service didn't successfully identify two channels but the structure of the output json wouldn't change. 
[channel_example.zip](https://github.com/purdy/aws-transcribe-transcript/files/2757789/channel_example.zip)

**Comment by purdy** [comment]
Thanks, Joel. It looks like the same text is happening on both channels? Not sure I understand how this works.

**Comment by joelprince25** [comment]
I can't share the audio files I'm working with because of confidentiality reasons. This sample file has the same voice on both channels so that's why it's the same. In reality, different channels will have different sounds, say, an agent and a customer will have different channels. I'm having some trouble finding good sample files to send you.

**Comment by purdy** [comment]
I don't really need the sample audio files. Can you provide me with a sample output? Can a channel have speaker identification, too?

Thanks!

**Comment by joelprince25** [comment]
Just created a pull request. No a channel cannot have speaker
identification. AWS Transcribe let's you do either channel identification
or speaker identification.

**Comment by purdy** [comment]
Merged in ... thanks, Joel!
